spring.application.name=PetCloudMapService
server.port=8120
spring.profiles.active=dev

logging.file.path=/Users/luohao/logs/petcloud-map

mybatis-plus.mapper-scan=com.petcloud.map.**.mapper
mybatis-plus.type-aliases-package=com.petcloud.map.domain.entity
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
