spring.application.name=PetCloudAiService
server.port=8119
spring.profiles.active=dev

logging.file.path=/Users/luohao/logs/petcloud-ai

mybatis-plus.mapper-scan=com.petcloud.ai.**.mapper
mybatis-plus.type-aliases-package=com.petcloud.ai.domain.entity
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
