-- ============================================
-- 伴宠云诊 - 完整数据库表创建脚本
-- 说明: 本文件是项目唯一保留的数据库建表 SQL
-- 仅保留 CREATE DATABASE / USE / CREATE TABLE 语句
-- ============================================

CREATE DATABASE IF NOT EXISTS `pet_cloud_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `pet_cloud_db`;

CREATE TABLE IF NOT EXISTS `wx_user` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `openid` VARCHAR(100) NOT NULL UNIQUE COMMENT '微信OpenID',
  `unionid` VARCHAR(100) DEFAULT NULL COMMENT '微信UnionID',
  `nickname` VARCHAR(100) DEFAULT NULL COMMENT '昵称',
  `avatar_url` VARCHAR(500) DEFAULT NULL COMMENT '头像URL',
  `gender` TINYINT UNSIGNED DEFAULT 0 COMMENT '性别: 0-未知 1-男 2-女',
  `phone` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  `status` TINYINT UNSIGNED DEFAULT 1 COMMENT '状态: 0-禁用 1-正常',
  `is_vip` TINYINT UNSIGNED DEFAULT 0 COMMENT '是否会员: 0-否 1-是',
  `vip_level` VARCHAR(20) DEFAULT NULL COMMENT '会员等级',
  `vip_start_time` DATETIME DEFAULT NULL COMMENT '会员开始时间',
  `vip_expire_time` DATETIME DEFAULT NULL COMMENT '会员到期时间',
  `vip_saving_amount` DECIMAL(10,2) DEFAULT 0 COMMENT '会员累计已省金额',
  `last_login_time` DATETIME DEFAULT NULL COMMENT '最后登录时间',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  INDEX `idx_openid` (`openid`),
  INDEX `idx_unionid` (`unionid`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='小程序用户表';

CREATE TABLE IF NOT EXISTS `vip_order` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '订单号',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `plan_id` VARCHAR(32) NOT NULL COMMENT '套餐ID',
  `plan_name` VARCHAR(50) NOT NULL COMMENT '套餐名称',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '支付金额',
  `duration_days` INT NOT NULL COMMENT '有效天数',
  `status` TINYINT UNSIGNED DEFAULT 1 COMMENT '状态: 0-待支付 1-已支付 2-已取消',
  `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
  `expire_time` DATETIME DEFAULT NULL COMMENT '到期时间',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  INDEX `idx_user_id` (`user_id`),
  UNIQUE KEY `uk_order_no` (`order_no`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会员订单表';

CREATE TABLE IF NOT EXISTS `user_pet` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `name` VARCHAR(50) NOT NULL COMMENT '宠物名称',
    `type` TINYINT UNSIGNED NOT NULL COMMENT '类型: 1-狗 2-猫 3-其他',
    `breed` VARCHAR(50) DEFAULT NULL COMMENT '品种',
    `gender` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '性别: 0-未知 1-公 2-母',
    `birthday` DATE DEFAULT NULL COMMENT '生日',
    `weight` DECIMAL(5,2) DEFAULT NULL COMMENT '体重(kg)',
    `avatar_url` VARCHAR(500) DEFAULT NULL COMMENT '宠物头像',
    `health_status` VARCHAR(200) DEFAULT NULL COMMENT '健康状况',
    `personality` VARCHAR(100) DEFAULT NULL COMMENT '宠物性格',
    `motto` VARCHAR(255) DEFAULT NULL COMMENT '座右铭/介绍',
    `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
    `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户宠物表';

CREATE TABLE IF NOT EXISTS `user_address` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `contact_name` VARCHAR(50) NOT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(20) NOT NULL COMMENT '联系电话',
  `province` VARCHAR(50) NOT NULL COMMENT '省份',
  `city` VARCHAR(50) NOT NULL COMMENT '城市',
  `district` VARCHAR(50) NOT NULL COMMENT '区/县',
  `detail_address` VARCHAR(200) NOT NULL COMMENT '详细地址',
  `is_default` TINYINT UNSIGNED DEFAULT 0 COMMENT '是否默认: 0-否 1-是',
  `longitude` DECIMAL(11,6) DEFAULT NULL COMMENT '经度',
  `latitude` DECIMAL(10,6) DEFAULT NULL COMMENT '纬度',
  `business_area` VARCHAR(100) DEFAULT NULL COMMENT '商圈',
  `door_no` VARCHAR(100) DEFAULT NULL COMMENT '门牌号',
  `raw_text` VARCHAR(500) DEFAULT NULL COMMENT '原始粘贴文本',
  `parsed_name` VARCHAR(50) DEFAULT NULL COMMENT '解析联系人',
  `parsed_phone` VARCHAR(20) DEFAULT NULL COMMENT '解析手机号',
  `map_address` VARCHAR(300) DEFAULT NULL COMMENT '地图地址描述',
  `address_tag` VARCHAR(50) DEFAULT NULL COMMENT '地址标签',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  INDEX `idx_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='收货地址表';

CREATE TABLE IF NOT EXISTS `course` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `title` VARCHAR(100) NOT NULL COMMENT '课程标题',
  `description` VARCHAR(500) DEFAULT NULL COMMENT '课程描述',
  `cover_url` VARCHAR(500) DEFAULT NULL COMMENT '封面图',
  `lesson_count` INT DEFAULT 0 COMMENT '课时数量',
  `student_count` INT DEFAULT 0 COMMENT '学习人数',
  `price` DECIMAL(10,2) DEFAULT 0 COMMENT '价格',
  `tag` VARCHAR(50) DEFAULT NULL COMMENT '标签: 入门/进阶/热门',
  `status` TINYINT UNSIGNED DEFAULT 1 COMMENT '状态: 0-下架 1-上架',
  `sort_order` INT DEFAULT 0 COMMENT '排序',
  `instructor_name` VARCHAR(50) DEFAULT NULL COMMENT '讲师姓名',
  `instructor_avatar` VARCHAR(255) DEFAULT NULL COMMENT '讲师头像',
  `instructor_bio` VARCHAR(500) DEFAULT NULL COMMENT '讲师简介',
  `chapters` JSON DEFAULT NULL COMMENT '章节列表JSON',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='课程表';

CREATE TABLE IF NOT EXISTS `course_progress` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id`       BIGINT UNSIGNED       NOT NULL                COMMENT '用户ID',
    `course_id`     BIGINT UNSIGNED       NOT NULL                COMMENT '课程ID',
    `chapter_id`    VARCHAR(50)  DEFAULT NULL             COMMENT '当前章节ID',
    `progress`      INT          DEFAULT 0               COMMENT '进度百分比 0-100',
    `watch_seconds` INT          DEFAULT 0               COMMENT '已观看秒数',
    `is_completed`  TINYINT UNSIGNED      DEFAULT 0               COMMENT '是否完成: 0否 1是',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_course` (`user_id`, `course_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='课程学习进度';

CREATE TABLE IF NOT EXISTS `course_review` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `course_id`     BIGINT UNSIGNED       NOT NULL                COMMENT '课程ID',
    `user_id`       BIGINT UNSIGNED       NOT NULL                COMMENT '用户ID',
    `user_nickname` VARCHAR(100) DEFAULT NULL             COMMENT '用户昵称',
    `rating`        TINYINT UNSIGNED      NOT NULL DEFAULT 5       COMMENT '评分 1-5',
    `content`       VARCHAR(500) DEFAULT NULL             COMMENT '评价内容',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_course` (`user_id`, `course_id`),
    INDEX `idx_course_id` (`course_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='课程评价';

CREATE TABLE IF NOT EXISTS `beauty_store` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(100) NOT NULL COMMENT '门店名称',
  `cover_url` VARCHAR(500) DEFAULT NULL COMMENT '封面图',
  `rating` DECIMAL(2,1) DEFAULT 0 COMMENT '评分',
  `distance` VARCHAR(20) DEFAULT NULL COMMENT '距离',
  `address` VARCHAR(200) NOT NULL COMMENT '地址',
  `tags` VARCHAR(200) DEFAULT NULL COMMENT '服务标签（逗号分隔）',
  `latitude` DECIMAL(10,6) DEFAULT NULL COMMENT '纬度',
  `longitude` DECIMAL(11,6) DEFAULT NULL COMMENT '经度',
  `phone` VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
  `business_hours` VARCHAR(100) DEFAULT NULL COMMENT '营业时间',
  `status` TINYINT UNSIGNED DEFAULT 1 COMMENT '状态: 0-关闭 1-营业',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='美容门店表';

CREATE TABLE IF NOT EXISTS `beauty_service` (
    `id`              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `store_id`        BIGINT UNSIGNED       NOT NULL             COMMENT '门店ID',
    `name`            VARCHAR(100) NOT NULL             COMMENT '服务名称',
    `description`     VARCHAR(500) NULL                 COMMENT '服务描述',
    `suitable_weight` VARCHAR(50)  NULL                 COMMENT '适合体重范围',
    `duration`        INT          NULL                 COMMENT '服务时长（分钟）',
    `price`           DECIMAL(10,2) NULL                COMMENT '服务价格',
    `status`          TINYINT UNSIGNED      NOT NULL DEFAULT 1   COMMENT '状态(0下架/1上架)',
    `sort_order`      INT          NOT NULL DEFAULT 0   COMMENT '排序权重',
    `creator_id`      BIGINT UNSIGNED       NULL COMMENT '创建人ID',
    `creator_name`    VARCHAR(64)  NULL COMMENT '创建人名称',
    `create_time`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`     BIGINT UNSIGNED       NULL COMMENT '修改人ID',
    `modifier_name`   VARCHAR(64)  NULL COMMENT '修改人名称',
    `modify_time`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    INDEX `idx_store_id` (`store_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='美容服务项目表';

CREATE TABLE IF NOT EXISTS `beauty_booking` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `store_id` BIGINT UNSIGNED NOT NULL COMMENT '门店ID',
  `pet_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '宠物ID',
  `booking_date` DATE NOT NULL COMMENT '预约日期',
  `booking_time` VARCHAR(10) NOT NULL COMMENT '预约时间段',
  `services` VARCHAR(200) DEFAULT NULL COMMENT '服务项目（逗号分隔）',
  `remark` VARCHAR(200) DEFAULT NULL COMMENT '备注',
  `status` TINYINT UNSIGNED DEFAULT 0 COMMENT '状态: 0-待确认 1-已确认 2-已完成 3-已取消',
  `before_photo` VARCHAR(500) DEFAULT NULL COMMENT '服务前照片URL',
  `after_photo` VARCHAR(500) DEFAULT NULL COMMENT '服务后照片URL',
  `service_photos` TEXT DEFAULT NULL COMMENT '服务过程照片JSON数组',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  INDEX `idx_user_id` (`user_id`),
  INDEX `idx_store_id` (`store_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='美容预约表';

CREATE TABLE IF NOT EXISTS `beauty_booking_log` (
    `id`            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `booking_id`    BIGINT UNSIGNED       NOT NULL             COMMENT '预约ID',
    `status`        TINYINT UNSIGNED      NOT NULL             COMMENT '状态值',
    `status_text`   VARCHAR(20)  NULL                 COMMENT '状态说明',
    `operator_id`   BIGINT UNSIGNED       NULL                 COMMENT '操作人ID',
    `remark`        VARCHAR(200) NULL                 COMMENT '备注',
    `creator_id`    BIGINT UNSIGNED       NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64)  NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64)  NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    INDEX `idx_booking_id` (`booking_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='美容预约操作日志表';

CREATE TABLE IF NOT EXISTS `message` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `type` VARCHAR(20) NOT NULL COMMENT '类型: system/consult/order/activity',
  `title` VARCHAR(100) NOT NULL COMMENT '标题',
  `content` VARCHAR(500) NOT NULL COMMENT '内容',
  `extra_data` VARCHAR(500) DEFAULT NULL COMMENT '额外数据(JSON)',
  `is_read` TINYINT UNSIGNED DEFAULT 0 COMMENT '是否已读: 0-未读 1-已读',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  INDEX `idx_user_id` (`user_id`),
  INDEX `idx_is_read` (`is_read`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='消息表';

CREATE TABLE IF NOT EXISTS `article` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `title` VARCHAR(100) NOT NULL COMMENT '文章标题',
  `cover_url` VARCHAR(500) DEFAULT NULL COMMENT '封面图',
  `summary` VARCHAR(200) DEFAULT NULL COMMENT '摘要',
  `content` TEXT NOT NULL COMMENT '文章内容',
  `tag` VARCHAR(50) DEFAULT NULL COMMENT '标签',
  `view_count` INT DEFAULT 0 COMMENT '浏览量',
  `like_count` INT DEFAULT 0 COMMENT '点赞数',
  `collect_count` INT DEFAULT 0 COMMENT '收藏数',
  `comment_count` INT DEFAULT 0 COMMENT '评论数',
  `publish_time` DATETIME DEFAULT NULL COMMENT '发布时间',
  `status` TINYINT UNSIGNED DEFAULT 1 COMMENT '状态: 0-草稿 1-已发布',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文章表';

CREATE TABLE IF NOT EXISTS `article_like` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `article_id` BIGINT UNSIGNED NOT NULL COMMENT '文章ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  UNIQUE KEY `uk_article_user` (`article_id`, `user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文章点赞记录表';

CREATE TABLE IF NOT EXISTS `article_collect` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `article_id` BIGINT UNSIGNED NOT NULL COMMENT '文章ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  UNIQUE KEY `uk_article_user` (`article_id`, `user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文章收藏记录表';

CREATE TABLE IF NOT EXISTS `article_comment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '评论ID',
  `article_id` BIGINT UNSIGNED NOT NULL COMMENT '文章ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `user_nickname` varchar(100) DEFAULT NULL COMMENT '用户昵称',
  `user_avatar` varchar(500) DEFAULT NULL COMMENT '用户头像',
  `content` varchar(500) NOT NULL COMMENT '评论内容',
  `parent_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '父评论ID（用于回复）',
  `reply_to_user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '回复目标用户ID',
  `reply_to_nickname` varchar(100) DEFAULT NULL COMMENT '回复目标用户昵称',
  `like_count` int DEFAULT '0' COMMENT '点赞数',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_article_id` (`article_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_parent_id` (`parent_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文章评论表';

CREATE TABLE IF NOT EXISTS `doctor` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(50) NOT NULL COMMENT '医生姓名',
  `avatar` VARCHAR(255) DEFAULT NULL COMMENT '头像',
  `title` VARCHAR(50) DEFAULT NULL COMMENT '职称',
  `specialty` VARCHAR(100) DEFAULT NULL COMMENT '专长',
  `department` VARCHAR(50) DEFAULT NULL COMMENT '科室',
  `experience` INT DEFAULT 0 COMMENT '从业年限',
  `description` VARCHAR(500) DEFAULT NULL COMMENT '医生简介',
  `hospital_name` VARCHAR(100) DEFAULT NULL COMMENT '所属医院',
  `consultation_fee` DECIMAL(10,2) DEFAULT 0 COMMENT '咨询费',
  `rating` DECIMAL(3,2) DEFAULT 5.0 COMMENT '评分',
  `consultation_count` INT DEFAULT 0 COMMENT '咨询次数',
  `tags` VARCHAR(200) DEFAULT NULL COMMENT '标签（逗号分隔）',
  `status` TINYINT UNSIGNED DEFAULT 1 COMMENT '状态: 0禁用 1启用',
  `sort_order` INT DEFAULT 0 COMMENT '排序',
  `online_status` TINYINT UNSIGNED DEFAULT 0 COMMENT '在线状态: 0离线 1在线',
  `avg_response_minutes` DECIMAL(10,2) DEFAULT NULL COMMENT '平均响应时长（分钟）',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='医生表';

CREATE TABLE IF NOT EXISTS `consultation` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `order_no` VARCHAR(32) NOT NULL COMMENT '咨询单号',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `user_nickname` VARCHAR(100) DEFAULT NULL COMMENT '用户昵称',
  `user_avatar` VARCHAR(500) DEFAULT NULL COMMENT '用户头像',
  `pet_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '宠物ID',
  `pet_name` VARCHAR(50) DEFAULT NULL COMMENT '宠物名称',
  `pet_type` TINYINT UNSIGNED DEFAULT NULL COMMENT '宠物类型：1狗 2猫 3其他',
  `doctor_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '医生ID',
  `doctor_name` VARCHAR(50) DEFAULT NULL COMMENT '医生姓名',
  `doctor_avatar` VARCHAR(255) DEFAULT NULL COMMENT '医生头像',
  `type` TINYINT UNSIGNED NOT NULL COMMENT '类型：1图文 2视频',
  `status` TINYINT UNSIGNED DEFAULT 0 COMMENT '状态：0待接单 1进行中 2已完成 3已取消',
  `description` TEXT COMMENT '病情描述',
  `images` JSON DEFAULT NULL COMMENT '病情图片',
  `fee` DECIMAL(10,2) DEFAULT 0 COMMENT '咨询费',
  `accept_time` DATETIME DEFAULT NULL COMMENT '接单时间',
  `finish_time` DATETIME DEFAULT NULL COMMENT '完成时间',
  `cancel_time` DATETIME DEFAULT NULL COMMENT '取消时间',
  `is_urgent` TINYINT UNSIGNED DEFAULT 0 COMMENT '是否紧急: 0普通 1紧急',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  KEY `idx_user_id` (`user_id`),
  KEY `idx_doctor_id` (`doctor_id`),
  KEY `idx_status` (`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='咨询记录表';

CREATE TABLE IF NOT EXISTS `consultation_message` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `consultation_id` BIGINT UNSIGNED NOT NULL COMMENT '咨询ID',
    `sender_id` BIGINT UNSIGNED NOT NULL COMMENT '发送者ID',
    `sender_type` TINYINT UNSIGNED NOT NULL COMMENT '发送者类型：1用户 2医生',
    `sender_name` VARCHAR(50) DEFAULT NULL COMMENT '发送者名称',
    `sender_avatar` VARCHAR(255) DEFAULT NULL COMMENT '发送者头像',
    `message_type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '消息类型：1文字 2图片 3语音',
    `content` TEXT DEFAULT NULL COMMENT '消息内容',
    `media_url` VARCHAR(500) DEFAULT NULL COMMENT '媒体文件URL',
    `is_read` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否已读',
    `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
    `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_consultation_id` (`consultation_id`),
    INDEX `idx_sender_id` (`sender_id`),
    INDEX `idx_is_read` (`is_read`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='咨询消息表';

CREATE TABLE IF NOT EXISTS `consultation_review` (
    `id`              BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `consultation_id` BIGINT UNSIGNED       NOT NULL                COMMENT '咨询ID',
    `doctor_id`       BIGINT UNSIGNED       NOT NULL                COMMENT '医生ID',
    `user_id`         BIGINT UNSIGNED       NOT NULL                COMMENT '用户ID',
    `user_nickname`   VARCHAR(100) DEFAULT NULL             COMMENT '用户昵称',
    `rating`          TINYINT UNSIGNED      NOT NULL DEFAULT 5       COMMENT '评分 1-5',
    `is_good`         TINYINT UNSIGNED      DEFAULT 1                COMMENT '是否好评: 0否 1是',
    `content`         VARCHAR(500) DEFAULT NULL             COMMENT '评价内容',
    `creator_id`      BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`    VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`     BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name`   VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_consultation` (`consultation_id`),
    INDEX `idx_doctor_id` (`doctor_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='咨询评价';

CREATE TABLE IF NOT EXISTS `health_record` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `pet_id` BIGINT UNSIGNED NOT NULL COMMENT '宠物ID',
  `pet_name` VARCHAR(50) COMMENT '宠物名称',
  `record_type` VARCHAR(20) NOT NULL COMMENT '记录类型：vaccine,checkup,medicine,surgery,other',
  `title` VARCHAR(100) COMMENT '标题',
  `content` TEXT COMMENT '详细内容',
  `hospital_name` VARCHAR(100) COMMENT '医院名称',
  `doctor_name` VARCHAR(50) COMMENT '医生姓名',
  `record_date` DATE COMMENT '记录日期',
  `next_date` DATE COMMENT '下次日期（如疫苗下次接种）',
  `images` JSON COMMENT '相关图片',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  INDEX `idx_pet_id` (`pet_id`),
  INDEX `idx_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='宠物健康档案';

CREATE TABLE IF NOT EXISTS `health_reminder` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id`       BIGINT UNSIGNED       NOT NULL                COMMENT '用户ID',
    `pet_id`        BIGINT UNSIGNED       NOT NULL                COMMENT '宠物ID',
    `pet_name`      VARCHAR(50)  DEFAULT NULL             COMMENT '宠物名称',
    `reminder_type` VARCHAR(20)  NOT NULL                 COMMENT '类型: vaccine,checkup,medicine,deworming,other',
    `title`         VARCHAR(100) NOT NULL                 COMMENT '提醒标题',
    `remind_date`   DATE         NOT NULL                 COMMENT '提醒日期',
    `is_done`       TINYINT UNSIGNED      DEFAULT 0                COMMENT '是否完成: 0否 1是',
    `note`          VARCHAR(255) DEFAULT NULL             COMMENT '备注',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_user_pet` (`user_id`, `pet_id`),
    INDEX `idx_remind_date` (`remind_date`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='健康提醒';

CREATE TABLE IF NOT EXISTS `system_config` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `config_key` VARCHAR(50) NOT NULL UNIQUE COMMENT '配置键',
  `config_value` TEXT COMMENT '配置值',
  `description` VARCHAR(200) COMMENT '描述',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统配置';

CREATE TABLE IF NOT EXISTS `product_category` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(50) NOT NULL COMMENT '分类名称',
  `icon` VARCHAR(50) DEFAULT NULL COMMENT '图标',
  `sort_order` INT DEFAULT 0 COMMENT '排序',
  `status` TINYINT UNSIGNED DEFAULT 1 COMMENT '状态: 0-禁用 1-启用',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品分类表';

CREATE TABLE IF NOT EXISTS `product` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `category_id` BIGINT UNSIGNED NOT NULL COMMENT '分类ID',
  `name` VARCHAR(100) NOT NULL COMMENT '商品名称',
  `cover_url` VARCHAR(500) DEFAULT NULL COMMENT '封面图',
  `image_urls` TEXT DEFAULT NULL COMMENT '商品图片（JSON数组）',
  `summary` VARCHAR(200) DEFAULT NULL COMMENT '商品简介',
  `price` DECIMAL(10,2) NOT NULL COMMENT '商品价格',
  `original_price` DECIMAL(10,2) DEFAULT NULL COMMENT '原价',
  `stock` INT DEFAULT 0 COMMENT '库存',
  `sales` INT DEFAULT 0 COMMENT '销量',
  `rating` DECIMAL(3,2) DEFAULT 5.0 COMMENT '评分',
  `review_count` INT DEFAULT 0 COMMENT '评价数',
  `tag` VARCHAR(50) DEFAULT NULL COMMENT '标签: 热门/新品/推荐',
  `shop_id` VARCHAR(64) DEFAULT NULL COMMENT '店铺标识',
  `shop_name` VARCHAR(100) DEFAULT NULL COMMENT '店铺名称',
  `service_text` VARCHAR(100) DEFAULT NULL COMMENT '服务文案',
  `default_spec` VARCHAR(100) DEFAULT NULL COMMENT '默认规格',
  `spec_groups_json` LONGTEXT DEFAULT NULL COMMENT '规格组配置(JSON)',
  `detail_content_json` LONGTEXT DEFAULT NULL COMMENT '详情内容配置(JSON)',
  `status` TINYINT UNSIGNED DEFAULT 1 COMMENT '状态: 0-下架 1-上架',
  `sort_order` INT DEFAULT 0 COMMENT '排序',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  KEY `idx_category_id` (`category_id`),
  KEY `idx_status` (`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品表';

CREATE TABLE IF NOT EXISTS `product_subscription` (
    `id`              BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id`         BIGINT UNSIGNED       NOT NULL                COMMENT '用户ID',
    `product_id`      BIGINT UNSIGNED       NOT NULL                COMMENT '商品ID',
    `sku_id`          BIGINT UNSIGNED       DEFAULT NULL             COMMENT 'SKU ID',
    `quantity`        INT          NOT NULL DEFAULT 1       COMMENT '数量',
    `cycle_days`      INT          NOT NULL                 COMMENT '配送周期（天）',
    `address_id`      BIGINT UNSIGNED       NOT NULL                 COMMENT '收货地址ID',
    `status`          TINYINT UNSIGNED      NOT NULL DEFAULT 0       COMMENT '状态: 0正常 1暂停 2取消',
    `next_order_date` DATE         DEFAULT NULL             COMMENT '下次下单日期',
    `discount_rate`   DECIMAL(5,2) DEFAULT 0.90             COMMENT '折扣率',
    `creator_id`      BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`    VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`     BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name`   VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id`    (`user_id`),
    INDEX `idx_product_id` (`product_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品订阅';

CREATE TABLE IF NOT EXISTS `order_info` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `order_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '订单号',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `total_amount` DECIMAL(10,2) NOT NULL COMMENT '订单总金额',
  `pay_amount` DECIMAL(10,2) NOT NULL COMMENT '实付金额',
  `receiver_name` VARCHAR(50) COMMENT '收货人',
  `receiver_phone` VARCHAR(20) COMMENT '收货电话',
  `receiver_address` VARCHAR(500) COMMENT '收货地址',
  `remark` VARCHAR(500) COMMENT '订单备注',
  `coupon_id` BIGINT UNSIGNED COMMENT '使用的优惠券ID',
  `coupon_discount` DECIMAL(10,2) DEFAULT 0 COMMENT '优惠券优惠金额',
  `status` TINYINT UNSIGNED DEFAULT 0 COMMENT '状态: 0-待付款 1-待发货 2-待收货 3-已完成 4-已取消',
  `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
  `ship_time` DATETIME DEFAULT NULL COMMENT '发货时间',
  `receive_time` DATETIME DEFAULT NULL COMMENT '收货时间',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_status` (`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单表';

CREATE TABLE IF NOT EXISTS `order_status_history` (
    `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    `order_id` BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
    `order_no` VARCHAR(64) DEFAULT NULL COMMENT '订单号',
    `from_status` TINYINT UNSIGNED DEFAULT NULL COMMENT '原状态',
    `to_status` TINYINT UNSIGNED DEFAULT NULL COMMENT '目标状态',
    `action` VARCHAR(50) NOT NULL COMMENT '动作标识',
    `operator_type` VARCHAR(30) DEFAULT NULL COMMENT '操作人类型',
    `operator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '操作人ID',
    `operator_name` VARCHAR(100) DEFAULT NULL COMMENT '操作人名称',
    `logistics_company` VARCHAR(50) DEFAULT NULL COMMENT '物流公司',
    `tracking_no` VARCHAR(64) DEFAULT NULL COMMENT '物流单号',
    `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
    `operate_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
    `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    KEY `idx_order_status_history_order` (`order_id`),
    KEY `idx_order_status_history_time` (`operate_time`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单状态历史';

CREATE TABLE IF NOT EXISTS `order_item` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `order_id` BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
  `product_id` BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  `product_name` VARCHAR(100) NOT NULL COMMENT '商品名称',
  `cover_url` VARCHAR(500) DEFAULT NULL COMMENT '商品封面',
  `shop_id` VARCHAR(64) DEFAULT NULL COMMENT '店铺标识',
  `shop_name` VARCHAR(100) DEFAULT NULL COMMENT '店铺名称',
  `service_text` VARCHAR(100) DEFAULT NULL COMMENT '服务文案',
  `spec_snapshot` VARCHAR(100) DEFAULT NULL COMMENT '规格快照',
  `sku_snapshot` VARCHAR(100) DEFAULT NULL COMMENT 'SKU快照',
  `price` DECIMAL(10,2) NOT NULL COMMENT '商品单价',
  `original_price` DECIMAL(10,2) DEFAULT NULL COMMENT '商品原价',
  `quantity` INT NOT NULL COMMENT '购买数量',
  `subtotal` DECIMAL(10,2) NOT NULL COMMENT '小计',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  KEY `idx_order_id` (`order_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单商品表';

CREATE TABLE IF NOT EXISTS `shopping_cart` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `product_id` BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  `quantity` INT NOT NULL DEFAULT 1 COMMENT '数量',
  `shop_id` VARCHAR(64) DEFAULT NULL COMMENT '店铺标识',
  `shop_name` VARCHAR(100) DEFAULT NULL COMMENT '店铺名称',
  `service_text` VARCHAR(100) DEFAULT NULL COMMENT '服务文案',
  `spec_label` VARCHAR(100) DEFAULT NULL COMMENT '规格说明',
  `sku_code` VARCHAR(64) DEFAULT NULL COMMENT 'SKU编码',
  `selected` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否选中',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态 active/invalid',
  `price_snapshot` DECIMAL(10,2) DEFAULT NULL COMMENT '价格快照',
  `original_price_snapshot` DECIMAL(10,2) DEFAULT NULL COMMENT '原价快照',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  UNIQUE KEY `uk_user_product_spec` (`user_id`, `product_id`, `spec_label`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='购物车';

CREATE TABLE IF NOT EXISTS `product_review` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_item_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '订单项ID',
    `product_id` BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `user_nickname` VARCHAR(50) DEFAULT NULL COMMENT '用户昵称',
    `user_avatar` VARCHAR(255) DEFAULT NULL COMMENT '用户头像',
    `rating` INT NOT NULL COMMENT '评分1-5',
    `content` TEXT DEFAULT NULL COMMENT '评价内容',
    `images` JSON DEFAULT NULL COMMENT '评价图片',
    `reply_content` TEXT DEFAULT NULL COMMENT '商家回复',
    `reply_time` DATETIME DEFAULT NULL COMMENT '回复时间',
    `like_count` INT NOT NULL DEFAULT 0 COMMENT '点赞数',
    `follow_up_content` TEXT DEFAULT NULL COMMENT '追评内容',
    `follow_up_time` DATETIME DEFAULT NULL COMMENT '追评时间',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间（编辑时间）',
    `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
    `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_product_id` (`product_id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_order_item_id` (`order_item_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品评价表';

CREATE TABLE IF NOT EXISTS `product_review_like` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `review_id` BIGINT UNSIGNED NOT NULL COMMENT '评价ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_user` (`review_id`,`user_id`),
  KEY `idx_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='评价点赞表';

CREATE TABLE IF NOT EXISTS `product_collection` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `product_id` BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  `product_name` varchar(200) DEFAULT NULL COMMENT '商品名称',
  `product_image` varchar(500) DEFAULT NULL COMMENT '商品图片',
  `product_price` decimal(10,2) DEFAULT NULL COMMENT '商品价格',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_product` (`user_id`,`product_id`),
  KEY `idx_product_id` (`product_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品收藏表';

CREATE TABLE IF NOT EXISTS `coupon` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(100) NOT NULL COMMENT '优惠券名称',
  `type` TINYINT UNSIGNED NOT NULL COMMENT '类型：1满减券 2折扣券',
  `discount_amount` DECIMAL(10,2) COMMENT '减免金额',
  `discount_rate` DECIMAL(5,2) COMMENT '折扣率',
  `min_amount` DECIMAL(10,2) DEFAULT 0 COMMENT '最低使用金额',
  `max_discount` DECIMAL(10,2) COMMENT '最大优惠金额(折扣券用)',
  `total_count` INT NOT NULL COMMENT '发行总量',
  `received_count` INT DEFAULT 0 COMMENT '已领取数量',
  `used_count` INT DEFAULT 0 COMMENT '已使用数量',
  `valid_days` INT NOT NULL COMMENT '有效天数',
  `start_time` DATETIME COMMENT '生效时间',
  `end_time` DATETIME COMMENT '失效时间',
  `description` VARCHAR(200) COMMENT '使用说明',
  `status` TINYINT UNSIGNED DEFAULT 1 COMMENT '状态：0禁用 1启用',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='优惠券';

CREATE TABLE IF NOT EXISTS `user_coupon` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `coupon_id` BIGINT UNSIGNED NOT NULL COMMENT '优惠券ID',
  `coupon_name` VARCHAR(100) COMMENT '优惠券名称',
  `coupon_type` TINYINT UNSIGNED COMMENT '类型：1满减券 2折扣券',
  `discount_amount` DECIMAL(10,2) COMMENT '减免金额',
  `discount_rate` DECIMAL(5,2) COMMENT '折扣率',
  `min_amount` DECIMAL(10,2) COMMENT '最低使用金额',
  `max_discount` DECIMAL(10,2) COMMENT '最大优惠金额',
  `status` TINYINT UNSIGNED DEFAULT 0 COMMENT '状态：0未使用 1已使用 2已过期',
  `use_time` DATETIME COMMENT '使用时间',
  `order_id` BIGINT UNSIGNED COMMENT '订单ID',
  `expire_time` DATETIME NOT NULL COMMENT '过期时间',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  INDEX `idx_user_id` (`user_id`),
  INDEX `idx_coupon_id` (`coupon_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户优惠券';

CREATE TABLE IF NOT EXISTS `payment_record` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_id` BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
    `order_no` VARCHAR(64) NOT NULL COMMENT '订单号',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `amount` DECIMAL(10,2) NOT NULL COMMENT '支付金额',
    `payment_method` VARCHAR(20) DEFAULT NULL COMMENT '支付方式：wechat,alipay,bank,credit',
    `payment_channel` VARCHAR(20) DEFAULT NULL COMMENT '支付渠道',
    `verify_type` VARCHAR(20) DEFAULT NULL COMMENT '验证方式',
    `status_detail` VARCHAR(100) DEFAULT NULL COMMENT '状态说明',
    `client_scene` VARCHAR(30) DEFAULT NULL COMMENT '客户端场景',
    `transaction_id` VARCHAR(64) DEFAULT NULL COMMENT '第三方交易号',
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态：0待支付 1已支付 2已退款',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
    `refund_time` DATETIME DEFAULT NULL COMMENT '退款时间',
    `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
    `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_order_id` (`order_id`),
    INDEX `idx_order_no` (`order_no`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_transaction_id` (`transaction_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付记录表';

CREATE TABLE IF NOT EXISTS `promotion` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` varchar(100) NOT NULL COMMENT '活动名称',
  `type` TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '类型：1满减',
  `threshold` decimal(10,2) NOT NULL COMMENT '满减门槛金额',
  `discount` decimal(10,2) NOT NULL COMMENT '优惠金额',
  `start_time` varchar(30) NOT NULL COMMENT '开始时间',
  `end_time` varchar(30) NOT NULL COMMENT '结束时间',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态：0禁用 1启用',
  `description` varchar(500) DEFAULT NULL COMMENT '活动描述',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='满减活动表';

CREATE TABLE IF NOT EXISTS `community_topic` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT  COMMENT '主键ID',
    `name`          VARCHAR(50)  NOT NULL                 COMMENT '话题名称',
    `icon`          VARCHAR(50)  DEFAULT '📌'             COMMENT '话题图标',
    `description`   VARCHAR(200) DEFAULT NULL             COMMENT '话题描述',
    `cover_url`     VARCHAR(500) DEFAULT NULL             COMMENT '话题封面',
    `post_count`    INT          NOT NULL DEFAULT 0       COMMENT '动态数量',
    `is_hot`        TINYINT UNSIGNED      NOT NULL DEFAULT 0       COMMENT '是否热门',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_name` (`name`),
    INDEX `idx_is_hot` (`is_hot`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='社区话题';

CREATE TABLE IF NOT EXISTS `community_post` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '发布者用户ID',
    `content` TEXT NOT NULL COMMENT '动态内容',
    `media_urls` JSON DEFAULT NULL COMMENT '媒体URL数组（JSON）',
    `media_type` VARCHAR(10) DEFAULT NULL COMMENT '媒体类型: image/video',
    `pet_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联宠物ID',
    `topic_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '话题ID',
    `like_count` INT NOT NULL DEFAULT 0 COMMENT '点赞数',
    `comment_count` INT NOT NULL DEFAULT 0 COMMENT '评论数',
    `share_count` INT NOT NULL DEFAULT 0 COMMENT '分享数',
    `collect_count` INT NOT NULL DEFAULT 0 COMMENT '收藏数',
    `is_pinned` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否置顶: 0否 1是',
    `is_hot` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否热门: 0否 1是',
    `visibility` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '可见性: 0-所有人可见 1-指定人可见 2-仅自己可见',
    `visible_user_ids` JSON DEFAULT NULL COMMENT '指定可见用户ID列表（JSON数组）',
    `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
    `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `is_deleted` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_create_time` (`create_time`),
    INDEX `idx_pinned` (`is_pinned`, `create_time`),
    INDEX `idx_hot` (`is_hot`, `create_time`),
    INDEX `idx_topic_id` (`topic_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='社区动态表';

CREATE TABLE IF NOT EXISTS `community_post_like` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT  COMMENT '主键ID',
    `post_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '动态ID',
    `user_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '用户ID',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_post_user` (`post_id`, `user_id`),
    INDEX `idx_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='社区动态点赞';

CREATE TABLE IF NOT EXISTS `community_post_collect` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT  COMMENT '主键ID',
    `post_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '帖子ID',
    `user_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '用户ID',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_post_user` (`post_id`, `user_id`),
    INDEX `idx_user` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='帖子收藏';

CREATE TABLE IF NOT EXISTS `community_comment` (
    `id`               BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT  COMMENT '主键ID',
    `post_id`          BIGINT UNSIGNED       NOT NULL                 COMMENT '动态ID',
    `user_id`          BIGINT UNSIGNED       NOT NULL                 COMMENT '评论者用户ID',
    `reply_to_id`      BIGINT UNSIGNED       DEFAULT NULL             COMMENT '回复目标评论ID',
    `reply_to_user_id` BIGINT UNSIGNED       DEFAULT NULL             COMMENT '回复目标用户ID',
    `content`          VARCHAR(500) NOT NULL                 COMMENT '评论内容',
    `like_count`       INT          DEFAULT 0                COMMENT '点赞数',
    `media_urls`       JSON         DEFAULT NULL             COMMENT '评论媒体URL数组',
    `media_type`       VARCHAR(10)  DEFAULT NULL             COMMENT '评论媒体类型: image/video',
    `is_deleted`       TINYINT UNSIGNED      NOT NULL DEFAULT 0       COMMENT '删除标识',
    `creator_id`       BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`     VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`      BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name`    VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_post_id` (`post_id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_create_time` (`create_time`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='社区动态评论';

CREATE TABLE IF NOT EXISTS `community_comment_like` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT  COMMENT '主键ID',
    `comment_id`    BIGINT UNSIGNED       NOT NULL                 COMMENT '评论ID',
    `user_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '用户ID',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_comment_user` (`comment_id`, `user_id`),
    INDEX `idx_user` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='评论点赞';

CREATE TABLE IF NOT EXISTS `community_post_share` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT  COMMENT '主键ID',
    `post_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '帖子ID',
    `user_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '用户ID',
    `share_type`    VARCHAR(20)  DEFAULT 'wechat'          COMMENT '分享类型: wechat,moments,link',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_post` (`post_id`),
    INDEX `idx_user` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='帖子分享记录';

CREATE TABLE IF NOT EXISTS `community_post_report` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT  COMMENT '主键ID',
    `post_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '帖子ID',
    `user_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '举报用户ID',
    `reason`        VARCHAR(200) NOT NULL                 COMMENT '举报原因',
    `reason_type`   VARCHAR(50)  DEFAULT NULL             COMMENT '举报类型: spam,abuse,inappropriate,other',
    `status`        TINYINT UNSIGNED      DEFAULT 0                COMMENT '状态: 0待处理 1已处理 2已驳回',
    `handler_id`    BIGINT UNSIGNED       DEFAULT NULL             COMMENT '处理人ID',
    `handler_remark` VARCHAR(500) DEFAULT NULL             COMMENT '处理备注',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_post` (`post_id`),
    INDEX `idx_user` (`user_id`),
    INDEX `idx_status` (`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='帖子举报';

CREATE TABLE IF NOT EXISTS `community_post_mention` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT  COMMENT '主键ID',
    `post_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '帖子ID',
    `comment_id`    BIGINT UNSIGNED       DEFAULT NULL             COMMENT '评论ID（如果是评论中的@）',
    `user_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '被@的用户ID',
    `mention_by`    BIGINT       NOT NULL                 COMMENT '@发起者ID',
    `is_read`       TINYINT UNSIGNED      DEFAULT 0                COMMENT '是否已读: 0否 1是',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_user` (`user_id`),
    INDEX `idx_post` (`post_id`),
    INDEX `idx_mention_by` (`mention_by`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='帖子@提及';

CREATE TABLE IF NOT EXISTS `user_follow` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT  COMMENT '主键ID',
    `follower_id`   BIGINT UNSIGNED       NOT NULL                 COMMENT '关注者ID',
    `following_id`  BIGINT UNSIGNED       NOT NULL                 COMMENT '被关注者ID',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_follow` (`follower_id`, `following_id`),
    INDEX `idx_following` (`following_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户关注关系';

CREATE TABLE IF NOT EXISTS `private_conversation` (
    `id`            BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT  COMMENT '主键ID',
    `user1_id`      BIGINT UNSIGNED       NOT NULL                 COMMENT '用户1 (较小的ID)',
    `user2_id`      BIGINT UNSIGNED       NOT NULL                 COMMENT '用户2 (较大的ID)',
    `last_message`  VARCHAR(500) DEFAULT NULL             COMMENT '最后一条消息内容',
    `last_time`     DATETIME     DEFAULT NULL             COMMENT '最后消息时间',
    `unread_1`      INT          DEFAULT 0                COMMENT '用户1未读数',
    `unread_2`      INT          DEFAULT 0                COMMENT '用户2未读数',
    `user1_hidden_time` DATETIME DEFAULT NULL             COMMENT '用户1隐藏时间',
    `user2_hidden_time` DATETIME DEFAULT NULL             COMMENT '用户2隐藏时间',
    `creator_id`    BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`  VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`   BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_users` (`user1_id`, `user2_id`),
    INDEX `idx_user2` (`user2_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='私信会话';

CREATE TABLE IF NOT EXISTS `private_message` (
    `id`              BIGINT UNSIGNED       NOT NULL AUTO_INCREMENT  COMMENT '主键ID',
    `conversation_id` BIGINT UNSIGNED       NOT NULL                 COMMENT '会话ID',
    `sender_id`       BIGINT UNSIGNED       NOT NULL                 COMMENT '发送者ID',
    `receiver_id`     BIGINT UNSIGNED       NOT NULL                 COMMENT '接收者ID',
    `content`         TEXT         NOT NULL                 COMMENT '消息内容',
    `msg_type`        VARCHAR(20)  DEFAULT 'text'           COMMENT '消息类型: text,image,voice',
    `is_read`         TINYINT UNSIGNED      DEFAULT 0                COMMENT '是否已读: 0否 1是',
    `creator_id`      BIGINT UNSIGNED       DEFAULT NULL COMMENT '创建人ID',
    `creator_name`    VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id`     BIGINT UNSIGNED       DEFAULT NULL COMMENT '修改人ID',
    `modifier_name`   VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_conversation` (`conversation_id`),
    INDEX `idx_sender` (`sender_id`),
    INDEX `idx_receiver` (`receiver_id`),
    INDEX `idx_create_time` (`create_time`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='私信消息';

CREATE TABLE IF NOT EXISTS `conversation` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `type` varchar(20) NOT NULL COMMENT '会话类型: ai_chat/doctor_consultation/customer_service',
  `target_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '目标ID(医生ID等)',
  `target_name` varchar(50) NOT NULL COMMENT '目标名称',
  `target_avatar` varchar(255) DEFAULT NULL COMMENT '目标头像',
  `last_message` varchar(200) DEFAULT NULL COMMENT '最后一条消息内容',
  `last_message_time` datetime DEFAULT NULL COMMENT '最后消息时间',
  `unread_count` int DEFAULT '0' COMMENT '未读消息数',
  `is_pinned` TINYINT UNSIGNED DEFAULT '0' COMMENT '是否置顶: 0否 1是',
  `status` varchar(20) DEFAULT 'active' COMMENT '状态: active/archived/deleted',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_type` (`user_id`,`type`),
  KEY `idx_last_message_time` (`last_message_time`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会话列表';

CREATE TABLE IF NOT EXISTS `task_definition` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_code` varchar(50) NOT NULL COMMENT '任务编码，唯一标识',
  `task_name` varchar(100) NOT NULL COMMENT '任务名称',
  `task_desc` varchar(500) DEFAULT NULL COMMENT '任务描述',
  `task_icon` varchar(50) DEFAULT NULL COMMENT '任务图标（emoji或图标名）',
  `task_type` TINYINT UNSIGNED DEFAULT '1' COMMENT '任务类型: 1-每日任务 2-每周任务 3-一次性任务',
  `points` int NOT NULL DEFAULT '0' COMMENT '完成奖励积分',
  `sort_order` int DEFAULT '0' COMMENT '排序顺序',
  `status` TINYINT UNSIGNED DEFAULT '1' COMMENT '状态: 0-禁用 1-启用',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_code` (`task_code`),
  KEY `idx_status` (`status`),
  KEY `idx_task_type` (`task_type`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务定义表';

CREATE TABLE IF NOT EXISTS `user_points` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `total_points` int NOT NULL DEFAULT '0' COMMENT '总积分',
  `used_points` int NOT NULL DEFAULT '0' COMMENT '已使用积分',
  `level` int DEFAULT '1' COMMENT '用户等级',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户积分表';

CREATE TABLE IF NOT EXISTS `points_history` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `points` INT NOT NULL COMMENT '变动积分（正数增加，负数减少）',
    `balance` INT NOT NULL COMMENT '变动后余额',
    `type` TINYINT UNSIGNED NOT NULL COMMENT '类型: 1-任务奖励 2-签到奖励 3-兑换消耗 4-其他',
    `related_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联ID（任务ID、订单ID等）',
    `remark` VARCHAR(200) DEFAULT NULL COMMENT '备注说明',
    `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
    `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_create_time` (`create_time`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='积分流水表';

CREATE TABLE IF NOT EXISTS `user_task` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `task_id` BIGINT UNSIGNED NOT NULL COMMENT '任务定义ID',
    `task_code` VARCHAR(50) NOT NULL COMMENT '任务编码',
    `points` INT NOT NULL DEFAULT 0 COMMENT '获得积分',
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态: 0-未完成 1-已完成',
    `complete_time` DATETIME DEFAULT NULL COMMENT '完成时间',
    `task_date` DATE NOT NULL COMMENT '任务日期（用于每日任务）',
    `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
    `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_task_date` (`user_id`, `task_id`, `task_date`),
    INDEX `idx_task_date` (`task_date`),
    INDEX `idx_user_task_date` (`user_id`, `task_date`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户任务记录表';

CREATE TABLE IF NOT EXISTS `ai_task` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `task_no` VARCHAR(64) NOT NULL COMMENT '任务编号',
  `task_type` VARCHAR(50) NOT NULL COMMENT '任务类型',
  `biz_type` VARCHAR(50) DEFAULT NULL COMMENT '业务类型',
  `biz_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '业务ID',
  `user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '用户ID',
  `guest_device_hash` VARCHAR(128) DEFAULT NULL COMMENT '游客设备哈希',
  `model_provider` VARCHAR(50) DEFAULT NULL COMMENT '模型提供方',
  `model_name` VARCHAR(100) DEFAULT NULL COMMENT '模型名称',
  `prompt_version` VARCHAR(50) DEFAULT NULL COMMENT 'Prompt版本',
  `template_version` VARCHAR(50) DEFAULT NULL COMMENT '模板版本',
  `status` VARCHAR(30) NOT NULL COMMENT '任务状态',
  `input_snapshot` LONGTEXT DEFAULT NULL COMMENT '输入快照',
  `output_snapshot` LONGTEXT DEFAULT NULL COMMENT '输出快照',
  `error_message` VARCHAR(500) DEFAULT NULL COMMENT '错误信息',
  `latency_ms` BIGINT DEFAULT NULL COMMENT '耗时毫秒',
  `trace_id` VARCHAR(64) DEFAULT NULL COMMENT '追踪ID',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  UNIQUE KEY `uk_ai_task_no` (`task_no`),
  KEY `idx_ai_task_user` (`user_id`),
  KEY `idx_ai_task_status` (`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI任务表';

CREATE TABLE IF NOT EXISTS `diagnosis_record` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `task_id` BIGINT UNSIGNED NOT NULL COMMENT 'AI任务ID',
  `user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '用户ID',
  `pet_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '宠物ID',
  `guest_device_hash` VARCHAR(128) DEFAULT NULL COMMENT '游客设备哈希',
  `symptom_tags_json` JSON DEFAULT NULL COMMENT '症状标签',
  `symptom_description` TEXT NOT NULL COMMENT '症状描述',
  `risk_level` VARCHAR(20) DEFAULT NULL COMMENT '风险等级',
  `summary` VARCHAR(500) DEFAULT NULL COMMENT '诊断摘要',
  `possible_causes_json` JSON DEFAULT NULL COMMENT '可能原因',
  `care_suggestions_json` JSON DEFAULT NULL COMMENT '护理建议',
  `next_actions_json` JSON DEFAULT NULL COMMENT '后续动作',
  `observation_table_json` JSON DEFAULT NULL COMMENT '观察表格',
  `should_consult_doctor` TINYINT UNSIGNED DEFAULT 0 COMMENT '是否建议就医',
  `status` VARCHAR(20) DEFAULT 'observing' COMMENT '病历状态',
  `diagnosis_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '诊断时间',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  KEY `idx_diag_task` (`task_id`),
  KEY `idx_diag_user_pet` (`user_id`, `pet_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI诊断记录';

CREATE TABLE IF NOT EXISTS `diagnosis_extracted_info` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `record_id` BIGINT UNSIGNED NOT NULL COMMENT '诊断记录ID',
  `primary_symptoms_json` JSON DEFAULT NULL COMMENT '主要症状',
  `duration_text` VARCHAR(100) DEFAULT NULL COMMENT '持续时间',
  `severity` VARCHAR(50) DEFAULT NULL COMMENT '严重程度',
  `suspected_issues_json` JSON DEFAULT NULL COMMENT '疑似问题',
  `affected_parts_json` JSON DEFAULT NULL COMMENT '影响部位',
  `follow_up_focus_json` JSON DEFAULT NULL COMMENT '复查重点',
  `extract_version` VARCHAR(50) DEFAULT NULL COMMENT '提取版本',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  KEY `idx_diag_extract_record` (`record_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI诊断关键信息提取';

CREATE TABLE IF NOT EXISTS `media_asset` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `asset_no` VARCHAR(64) NOT NULL COMMENT '资产编号',
  `owner_type` VARCHAR(50) DEFAULT NULL COMMENT '归属类型',
  `owner_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '归属ID',
  `user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '用户ID',
  `media_type` VARCHAR(20) NOT NULL COMMENT '媒体类型',
  `url` VARCHAR(500) NOT NULL COMMENT '文件URL',
  `mime_type` VARCHAR(100) DEFAULT NULL COMMENT 'mime类型',
  `file_size` BIGINT DEFAULT NULL COMMENT '文件大小',
  `upload_status` VARCHAR(30) DEFAULT 'uploaded' COMMENT '上传状态',
  `moderation_status` VARCHAR(20) DEFAULT 'pass' COMMENT '审核状态',
  `risk_tags_json` JSON DEFAULT NULL COMMENT '风险标签',
  `reason` VARCHAR(255) DEFAULT NULL COMMENT '审核说明',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  UNIQUE KEY `uk_media_asset_no` (`asset_no`),
  KEY `idx_media_user` (`user_id`),
  KEY `idx_media_status` (`moderation_status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='媒体资产表';

CREATE TABLE IF NOT EXISTS `featured_content_draft` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `draft_date` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '草稿日期',
  `source_type` VARCHAR(30) NOT NULL COMMENT '来源类型',
  `source_id` BIGINT UNSIGNED NOT NULL COMMENT '来源ID',
  `title` VARCHAR(120) NOT NULL COMMENT '标题',
  `summary` VARCHAR(300) DEFAULT NULL COMMENT '摘要',
  `tag` VARCHAR(50) DEFAULT NULL COMMENT '标签',
  `reason_label` VARCHAR(100) DEFAULT NULL COMMENT '推荐理由',
  `cover_url` VARCHAR(500) DEFAULT NULL COMMENT '封面',
  `ranking_score` INT DEFAULT 0 COMMENT '排序分',
  `status` VARCHAR(30) DEFAULT 'draft' COMMENT '草稿状态',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  KEY `idx_featured_draft_date` (`draft_date`),
  KEY `idx_featured_status` (`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='首页精选草稿';

CREATE TABLE IF NOT EXISTS `featured_content_publish` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `publish_date` DATE DEFAULT NULL COMMENT '发布日期',
    `position_no` INT DEFAULT 0 COMMENT '首页排序位次',
    `draft_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '来源草稿ID',
    `title` VARCHAR(120) NOT NULL COMMENT '内容标题',
    `summary` VARCHAR(500) DEFAULT NULL COMMENT '内容摘要',
    `tag` VARCHAR(50) DEFAULT NULL COMMENT '标签',
    `reason_label` VARCHAR(50) DEFAULT NULL COMMENT '推荐理由标签',
    `cover_url` VARCHAR(500) DEFAULT NULL COMMENT '封面图',
    `target_page` VARCHAR(50) DEFAULT NULL COMMENT '跳转页面类型',
    `target_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '跳转目标ID',
    `status` VARCHAR(20) NOT NULL DEFAULT 'published' COMMENT '状态: published/offline',
    `start_time` DATETIME NOT NULL COMMENT '生效开始时间',
    `end_time` DATETIME DEFAULT NULL COMMENT '生效结束时间',
    `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
    `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
    `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
    `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    KEY `idx_featured_publish_status_time` (`status`, `start_time`, `end_time`),
    KEY `idx_featured_publish_date_position` (`publish_date`, `position_no`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='首页精选内容发布表';

CREATE TABLE IF NOT EXISTS `ai_chat_message` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `conversation_id` BIGINT UNSIGNED NOT NULL COMMENT '会话ID',
  `role` varchar(20) NOT NULL COMMENT '角色: user/assistant',
  `content` text NOT NULL COMMENT '消息内容',
  `model_type` varchar(20) DEFAULT NULL COMMENT '模型类型: qwen/deepseek',
  `creator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(64) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_conversation` (`user_id`,`conversation_id`),
  KEY `idx_conversation_id` (`conversation_id`),
  KEY `idx_create_time` (`create_time`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI聊天记录';
