# 应用名称
spring.application.name=PetCloudShopService
server.port=8118
spring.profiles.active=dev

# 日志配置
logging.file.path=/Users/luohao/logs/petcloud-shop

# MyBatis-Plus 配置
mybatis-plus.mapper-scan=com.petcloud.shop.**.mapper
mybatis-plus.type-aliases-package=com.petcloud.shop.domain.entity
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
