CREATE TABLE IF NOT EXISTS `featured_content_publish` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `publish_date` DATE DEFAULT NULL COMMENT '发布日期',
  `position_no` INT DEFAULT 0 COMMENT '首页排序位次',
  `draft_id` BIGINT DEFAULT NULL COMMENT '来源草稿ID',
  `title` VARCHAR(120) NOT NULL COMMENT '内容标题',
  `summary` VARCHAR(500) DEFAULT NULL COMMENT '内容摘要',
  `tag` VARCHAR(50) DEFAULT NULL COMMENT '标签',
  `reason_label` VARCHAR(50) DEFAULT NULL COMMENT '推荐理由标签',
  `cover_url` VARCHAR(500) DEFAULT NULL COMMENT '封面图',
  `target_page` VARCHAR(50) DEFAULT NULL COMMENT '跳转页面类型',
  `target_id` BIGINT DEFAULT NULL COMMENT '跳转目标ID',
  `status` VARCHAR(20) NOT NULL DEFAULT 'published' COMMENT '状态: published/offline',
  `start_time` DATETIME NOT NULL COMMENT '生效开始时间',
  `end_time` DATETIME DEFAULT NULL COMMENT '生效结束时间',
  `creator_id` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `creator_name` VARCHAR(50) DEFAULT NULL COMMENT '创建人名称',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifier_id` BIGINT DEFAULT NULL COMMENT '修改人ID',
  `modifier_name` VARCHAR(50) DEFAULT NULL COMMENT '修改人名称',
  `modify_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_featured_publish_status_time` (`status`, `start_time`, `end_time`),
  KEY `idx_featured_publish_date_position` (`publish_date`, `position_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='首页精选内容发布表';
