spring.application.name=PetCloudMediaService
server.port=8121
spring.profiles.active=dev

logging.file.path=/Users/luohao/logs/petcloud-media

mybatis-plus.mapper-scan=com.petcloud.media.**.mapper
mybatis-plus.type-aliases-package=com.petcloud.media.domain.entity
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
